### ISSUE TITLE
should be mod rather than mp3

### ISSUE THREAD

**Issue by rofl0r** [0xabad1dea/glorytales#1]
with your music, a simple game becomes a 50MB download, while it would be a few hundred KB with mod (fasttracker format or whatever) music.

**Comment by 0xabad1dea** [comment]
You have got to be kidding me 

I have written dozens of 8KB chiptunes, these are at the opposite end of the conceptual scale and intended to be high-realism high-fidelity, they're provided at absurdly high bitrate so you can recompress if you need to and don't if you don't

but I'm pretty sure you're trolling me so
